# URL Simplificada (Removi os caches que causaram o erro de leitura)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# Credenciais
spring.datasource.username=postgres.sexrjimlzpljwpagowyl
spring.datasource.password=ra050306@___

# Driver e Dialeto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o cache de statements do lado do Hibernate (Importante para o Supabase)
spring.jpa.properties.hibernate.prepare_all_queries=false