# aqui eu faço o protocolo de comunicacao na porta local desse compt com o nome q eu dei la no banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare

# especie de usuario que vem padrao qnd cria o banco
spring.datasource.username=postgres

# minha senha do database
spring.datasource.password=12345678 

# ele faz a funcao de ta sempre atualizando la no banco de dados
spring.jpa.hibernate.ddl-auto=update

# ele vai basicamente mostrar os comandos sqls que estao sendo utilizados
spring.jpa.show-sql=true

# ele faz a traducao para ser possivel entender
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect